"""Visualizations dashboard page."""

import sys
from pathlib import Path
import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

from app.components.sidebar import setup_page
from app.components.charts import render_chart
from app.services.session import initialize_session, get_workflow_result


def main() -> None:
    """Render the visualizations page."""
    initialize_session()
    setup_page("Visualizations")

    st.title("📈 Auto-Generated Visual Analytics")
    st.markdown(
        """
        These visual charts were automatically selected, customized, and generated by the 
        Visualization Agent based on dataset types, correlations, and ML task properties.
        """
    )
    st.divider()

    result = get_workflow_result()
    if not result:
        st.info("No active workflow result. Please upload a dataset and run the pipeline on the Upload page.")
        return

    viz_result = getattr(result.state, "visualization_result", None)
    if not viz_result or not viz_result.is_success:
        st.warning("No generated visualizations found in the execution state.")
        return

    # Loop over charts and render each using our rich component
    report = viz_result.report
    for chart_meta in report.charts:
        render_chart(chart_meta)
        st.divider()

    # Renders Metadata
    meta = report.metadata
    if meta:
        with st.expander("🛠️ Visualization Telemetry Details", expanded=False):
            st.markdown(
                f"""
                * **Creation Timestamp:** `{meta.created_at}`
                * **Design Theme Applied:** `{meta.theme.title()}`
                * **Dataset Fingerprint Hash:** `{meta.dataset_hash or "Unknown"}`
                * **Charts Saved In Directory:** `{viz_result.output_directory}`
                * **Agent Processing Time:** `{viz_result.duration_seconds:.2f}s`
                """
            )


if __name__ == "__main__":
    main()
